// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/contracts/service.go

// Package mock_contracts is a generated GoMock package.
package mock_contracts

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/htrandev/metrics/internal/model"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockService) Get(ctx context.Context, name string) (model.MetricDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, name)
	ret0, _ := ret[0].(model.MetricDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockServiceMockRecorder) Get(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockService)(nil).Get), ctx, name)
}

// GetAll mocks base method.
func (m *MockService) GetAll(ctx context.Context) ([]model.MetricDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]model.MetricDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockServiceMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockService)(nil).GetAll), ctx)
}

// Ping mocks base method.
func (m *MockService) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockServiceMockRecorder) Ping(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockService)(nil).Ping), ctx)
}

// Store mocks base method.
func (m *MockService) Store(ctx context.Context, metric *model.MetricDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, metric)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockServiceMockRecorder) Store(ctx, metric interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockService)(nil).Store), ctx, metric)
}

// StoreMany mocks base method.
func (m *MockService) StoreMany(ctx context.Context, metric []model.MetricDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreMany", ctx, metric)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreMany indicates an expected call of StoreMany.
func (mr *MockServiceMockRecorder) StoreMany(ctx, metric interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreMany", reflect.TypeOf((*MockService)(nil).StoreMany), ctx, metric)
}

// StoreManyWithRetry mocks base method.
func (m *MockService) StoreManyWithRetry(ctx context.Context, metric []model.MetricDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreManyWithRetry", ctx, metric)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreManyWithRetry indicates an expected call of StoreManyWithRetry.
func (mr *MockServiceMockRecorder) StoreManyWithRetry(ctx, metric interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreManyWithRetry", reflect.TypeOf((*MockService)(nil).StoreManyWithRetry), ctx, metric)
}
