package main

const genTemplate = `
// Code generated by go generate; DO NOT EDIT.
// This file was generated by cmd/reset/main.go

package {{.Package}}

{{range .Structs}}
{{ $struct := . }}

func ({{.Recv}} *{{.Name}}) Reset() {
	{{range .Fields}} 
        {{if .HasReset}} 
            {{if .IsPointer}}
                if {{ $struct.Recv }}.{{.Name}} != nil { 
                    {{ $struct.Recv }}.{{.Name}}.Reset() 
                }
            {{else}}
                {{ $struct.Recv }}.{{.Name}}.Reset()
            {{end}}
        {{else if .IsSlice}} 
            {{ $struct.Recv }}.{{.Name}} = {{ $struct.Recv }}.{{.Name}}[:0]
        {{else if .IsMap}} 
			clear({{ $struct.Recv }}.{{.Name}})
        {{else if .IsPointer}} 
			if {{ $struct.Recv }}.{{.Name}} != nil {
				*{{ $struct.Recv }}.{{.Name}} = {{.Zero}}
			}
        {{else}} 
            {{ $struct.Recv }}.{{.Name}} = {{.Zero}}
        {{end}}
	{{end}}
}
{{end}}
`
