// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package audit

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonAb7d04DecodeGithubComHtrandevMetricsInternalAudit(in *jlexer.Lexer, out *AuditInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ts":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Timestamp = int64(in.Int64())
			}
		case "metrics":
			if in.IsNull() {
				in.Skip()
				out.Metrics = nil
			} else {
				in.Delim('[')
				if out.Metrics == nil {
					if !in.IsDelim(']') {
						out.Metrics = make([]string, 0, 4)
					} else {
						out.Metrics = []string{}
					}
				} else {
					out.Metrics = (out.Metrics)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.Metrics = append(out.Metrics, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "ip_address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IP = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAb7d04EncodeGithubComHtrandevMetricsInternalAudit(out *jwriter.Writer, in AuditInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ts\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Timestamp))
	}
	{
		const prefix string = ",\"metrics\":"
		out.RawString(prefix)
		if in.Metrics == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Metrics {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"ip_address\":"
		out.RawString(prefix)
		out.String(string(in.IP))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AuditInfo) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonAb7d04EncodeGithubComHtrandevMetricsInternalAudit(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AuditInfo) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAb7d04EncodeGithubComHtrandevMetricsInternalAudit(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AuditInfo) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonAb7d04DecodeGithubComHtrandevMetricsInternalAudit(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AuditInfo) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAb7d04DecodeGithubComHtrandevMetricsInternalAudit(l, v)
}
